name: LDBC-SNB-Interactive-V1-Benchmark

env:
  RUNTIME_CHECKS: 1
  WERROR: 1

on: push

jobs:
  benchmark:
    name: benchmark
    runs-on: kuzu-self-hosted-benchmarking
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Build Kuzu
      run: |
        pip3 install -r tools/python_api/requirements_dev.txt
        make python NUM_THREADS=$(nproc)
        make java NUM_THREADS=$(nproc)
    
    - name: Clone and build driver
      run: |
        git clone https://github.com/ldbc/ldbc_snb_interactive_v1_driver
        cd ldbc_snb_interactive_v1_driver
        scripts/install.sh
    
    - name: Download and decompress dataset
      run: |
        mkdir interactive_v1_dataset
        cd interactive_v1_dataset
        curl --silent --fail -k "https://repository.surfsara.nl/datasets/cwi/snb/files/substitution_parameters/substitution_parameters-sf1.tar.zst" | tar -xv --use-compress-program=unzstd
        curl --silent --fail -k "https://repository.surfsara.nl/datasets/cwi/ldbc-snb-interactive-v1-datagen-v100/files/social_network-sf1-CsvComposite-LongDateFormatter.tar.zst" | tar -xv --use-compress-program=unzstd
    
    - name: Clone and build implementation
      run: |
        git clone https://github.com/mxwli/ldbc_snb_interactive_v1_kuzu_impl
        cd ldbc_snb_interactive_v1_kuzu_impl/kuzu/src/main/resources/
        cp {{ github.workspace }}/tools/java_api/build/kuzu_java.jar .
        cd {{ github.workspace }}/ldbc_snb_interactive_v1_kuzu_impl
        scripts/build.sh

    - name: Load database
      run: |
        cd ldbc_snb_interactive_v1_kuzu_impl/kuzu
        export KUZU_CSV_DIR="{{ github.workspace }}/interactive_v1_dataset/social_network-sf1-CsvComposite-LongDateFormatter/"
        workflow_scripts/load-in-one-step.sh
    

    - name: Run benchmark
      run: |
        cd ldbc_snb_interactive_v1_kuzu_impl/kuzu
        echo "ldbc.snb.interactive.updates_dir={{ github.workspace }}/interactive_v1_dataset/social_network-sf1-CsvComposite-LongDateFormatter/" >> driver/benchmark.properties
        echo "ldbc.snb.interactive.parameters_dir={{ github.workspace }}/interactive_v1_dataset/substitution_parameters-sf1/" >> driver/benchmark.properties
        driver/benchmark.sh

    - name: Submit Results
      uses: actions/upload-artifact@v3
      with:
        name: LDBC-SNB-interactive-v1-results
        path: ldbc_snb_interactive_v1_kuzu_impl/kuzu/results/LDBC-SNB-results.json
